env: development
platform: local
app:
  name: kms
  version: 0.1
  profilingEnabled: false
logger:
  logLevel: debug
db:
  host: localhost
  user: admin
  password: ndtd1234
  dbName: local
  port: 7432
  migration: true
  # searchPath: local

cache:
  url: redis://default:1234@localhost:16379/0
  poolSize: 10
  useTSL: false
      
session:
  basicAuth:
    username: admin
    password: ndtd1234
  jwt:
    secret: local
    accessTokenExp: 14400
    refreshTokenExp: 86400

httpServer:
  port: 8080
  cors:
    allowOrigins:
      - http://localhost:3000 
