version: '3'
services:
  golang-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=postgre
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=ndtd1234
      - POSTGRES_DB=local
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=1234
    ports:
      - 8080:8080
    depends_on:
      - postgre
      - redis

  postgre:
    container_name: postgre_local
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=ndtd1234
      - POSTGRES_DB=local
    ports:
      - 7432:5432
    restart: always

  redis:
    image: redis:6.0.8-alpine
    ports:
      - 16379:6379
    volumes:
      - redisconf:/redis.conf
      - redis:/var/lib/redis
    command: redis-server --requirepass 1234

volumes:
  redisconf:
  redis:
