// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"context"
	"kms/app/external/persistence/database/repository"
	"kms/app/usecase/auth"
)

// Injectors from wire.go:

func InjectedAuthUseCase(ctx context.Context, provider *Provider) auth.IUseCase {
	db := provider.DB
	postgresRepository := repository.NewPostgresRepository(db)
	iUseCase := auth.NewUseCase(postgresRepository)
	return iUseCase
}
