// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"context"
	"kms/app/external/persistence/database/repository"
	"kms/app/usecase/auth"
	"kms/app/usecase/chat"
	"kms/app/usecase/class"
	"kms/app/usecase/cron"
	"kms/app/usecase/dish"
	"kms/app/usecase/user"
)

// Injectors from wire.go:

func InjectedAuthUseCase(ctx context.Context, provider *Provider) auth.IUseCase {
	db := provider.DB
	postgresRepository := repository.NewPostgresRepository(db)
	iUseCase := auth.NewUseCase(postgresRepository)
	return iUseCase
}

func InjectedUserUseCase(ctx context.Context, provider *Provider) user.IUseCase {
	db := provider.DB
	postgresRepository := repository.NewPostgresRepository(db)
	iUseCase := user.NewUseCase(postgresRepository)
	return iUseCase
}

func InjectedChatUseCase(ctx context.Context, provider *Provider) chat.IUseCase {
	db := provider.DB
	postgresRepository := repository.NewPostgresRepository(db)
	iUseCase := chat.NewUseCase(postgresRepository)
	return iUseCase
}

func InjectedClassUseCase(ctx context.Context, provider *Provider) class.IUseCase {
	db := provider.DB
	postgresRepository := repository.NewPostgresRepository(db)
	iUseCase := class.NewUseCase(postgresRepository)
	return iUseCase
}

func InjectedCronUseCase(ctx context.Context, provider *Provider) cron.IUseCase {
	db := provider.DB
	postgresRepository := repository.NewPostgresRepository(db)
	iUseCase := cron.NewUseCase(postgresRepository)
	return iUseCase
}

func InjectedDishUseCase(ctx context.Context, provider *Provider) dish.IUseCase {
	db := provider.DB
	postgresRepository := repository.NewPostgresRepository(db)
	iUseCase := dish.NewUseCase(postgresRepository)
	return iUseCase
}
